apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kustomize-sample
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kustomize-sample-dev.variant.dev
    secretName: kustomize-sample-dev-tls
  rules:
  - host: kustomize-sample-dev.variant.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kustomize-sample
            port:
              number: 80
